### ISSUE TITLE
dev / www gitignored

### ISSUE THREAD

**Issue by matteodem** [fabrica-wp/fabrica-dev-kit#12]
Hi, what is exactly the idea behind the dev and www folder being git ignored? Or is that only to keep you from committing unwanted files into this project?

**Comment by fewerflatlands** [comment]
Hi @matteodem yes, it's so an individual install's files never get committed to the FDK main repo. 

I suppose you are asking because you want to have version control on your own project. For this just do `git init` *within* the dev folder ([as mentioned here](https://github.com/fabrica-wp/fabrica-dev-kit#version-control)). All your project source files are within `dev`, so there's no need to have the contents of `www` in version control (it can be rebuilt easily in a different environment if required).

Does that make sense? Let me know if you still have a doubt.

**Comment by matteodem** [comment]
Yeah that makes sense, thanks for the explanation! Shouldn't the `git init` step be described here? https://github.com/fabrica-wp/fabrica-dev-kit#running-the-build-script--watch-during-active-development

**Comment by fewerflatlands** [comment]
It's just underneath that – but version control it's not part of the build script, and is a separate process / action to running `gulp`, so it makes sense to us that it's in a separate section.

Thanks for trying FDK and let us know if you have any other questions / feedback.
