### ISSUE TITLE
Standalone theme without local Docker environment

### ISSUE THREAD

**Issue by inorbita** [fabrica-wp/fabrica-dev-kit#16]
I would love to use just the theme (including Browsersync, Gulp etc.), but without the local Docker environment. Since I run my own local dev env. Would that be easily achievable?

**Comment by fewerflatlands** [comment]
Hi @inorbita. We'd really recommend using the full kit to keep projects isolated, and for ease of setup. However there's no reason you couldn't use the theme and build tools separately you would have to do the relevant parts of the set up manually. The process would roughly be:

1. Clone repo.
2. Move `provision/dev` folder to wherever you want to work from and delete everything else.
3. Run `npm install` in that folder.
4. Manually render all the `.erb` templates (open them, replace values with your project values, then save without the `.erb` extension).
5. Run `npm install` in the `src/` folder.
6. Run `compose install` in the `src/includes/` folder.
7. Modify `gulpfile.js` to remove `wpconfig()` task and set the destination paths so that the build script compiles to your active WP folder.

Hopefully that'll be enough to get you there. Really this usage is unsupported though, so I'm not sure we would be able to offer further technical support. It would be better to use the whole kit! We'll soon be releasing some significant updates, so keep an eye out.
