### ISSUE TITLE
[BUG] ACF json files aren't being deployed correctly

### ISSUE THREAD

**Issue by zomars** [fabrica-wp/fabrica-dev-kit#29]
Whenever I use wordmove to deploy to a remote server, the acf-json is being deployed as a symbolic link instead of the actual folder, preventing me to sync the newly added fields.

<img width="597" alt="captura de pantalla 2017-08-18 a las 10 57 47" src="https://user-images.githubusercontent.com/3504472/29469150-4cb3eef4-8404-11e7-9078-3cd474ca83de.png">

**Comment by zomars** [comment]
On another note, when I manually upload the folder via FTP the sync starts working again.

**Comment by zomars** [comment]
Also, adding the `-L` flag to `rsync_options` in the `wordmove.yml` file resolves the issue. I don't know is this should be a default so it can work out of the box.

**Comment by tiojoca** [comment]
We prefer to leave the Wordmove server configuration for the user to set and only set the local information (like local paths and URLs/ports) since one user might choose to use FTP while another uses SSH, for example. But we've added the `-L` flag to the default commented `rsync_options` field in `wordmove.yml`.
