### ISSUE TITLE
Adding wp plugins during development.

### ISSUE THREAD

**Issue by samburgers** [fabrica-wp/fabrica-dev-kit#7]
Hi,

What is the recommended way to add/remove wordpress plugins after initial setup, or during dev?

**Comment by fewerflatlands** [comment]
Either in the usual way through the admin, or put them straight into `www/wp-content/plugins/`.

**Comment by samburgers** [comment]
Appreciate the quick replies! I had figured plugins might be Composer managed. Thanks for clearing that up.

**Comment by fewerflatlands** [comment]
Composer is there in `dev/src/includes/` for any PHP dependencies your theme might have. But WP plugins work normally. 

(In the specific case of Timber, which can be installed both as a plugin and a Composer dependency, we prefer the latter, because it's pretty essential to our workflow, but you don't have to use either!)
